// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['main']['App']['AddProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateDrops(arg1, arg2) {
  return window['go']['main']['App']['UpdateDrops'](arg1, arg2);
}

export function UpdateProfileGlowColor(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileGlowColor'](arg1, arg2);
}

export function UpdateProfileName(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileName'](arg1, arg2);
}
