// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['main']['App']['AddProfile'](arg1);
}

export function CreateLearnSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLearnSession'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function EndSession(arg1, arg2) {
  return window['go']['main']['App']['EndSession'](arg1, arg2);
}

export function GetClassSessions(arg1) {
  return window['go']['main']['App']['GetClassSessions'](arg1);
}

export function GetDatabaseExplorerData(arg1) {
  return window['go']['main']['App']['GetDatabaseExplorerData'](arg1);
}

export function GetDueFactoids(arg1) {
  return window['go']['main']['App']['GetDueFactoids'](arg1);
}

export function GetFactoids(arg1) {
  return window['go']['main']['App']['GetFactoids'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSessionStatistics(arg1, arg2) {
  return window['go']['main']['App']['GetSessionStatistics'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListSessionsByActivity(arg1) {
  return window['go']['main']['App']['ListSessionsByActivity'](arg1);
}

export function ProcessTextToFactoids(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessTextToFactoids'](arg1, arg2, arg3);
}

export function ProcessUserMessage(arg1, arg2) {
  return window['go']['main']['App']['ProcessUserMessage'](arg1, arg2);
}

export function RecordAIChatHistory(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RecordAIChatHistory'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RecordAIParserHistory(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RecordAIParserHistory'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RecordAIUploadHistory(arg1, arg2) {
  return window['go']['main']['App']['RecordAIUploadHistory'](arg1, arg2);
}

export function ResumeSession(arg1, arg2) {
  return window['go']['main']['App']['ResumeSession'](arg1, arg2);
}

export function StartSessionConversation(arg1) {
  return window['go']['main']['App']['StartSessionConversation'](arg1);
}

export function UpdateDrops(arg1, arg2) {
  return window['go']['main']['App']['UpdateDrops'](arg1, arg2);
}

export function UpdateFactoidReview(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateFactoidReview'](arg1, arg2, arg3);
}

export function UpdateProfileGlowColor(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileGlowColor'](arg1, arg2);
}

export function UpdateProfileName(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileName'](arg1, arg2);
}

export function UpdateSessionChatHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSessionChatHistory'](arg1, arg2, arg3);
}
