// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function AddProfile(arg1:db.Profile):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetProfiles():Promise<Array<db.Profile>>;

export function Greet(arg1:string):Promise<string>;

export function UpdateDrops(arg1:string,arg2:number):Promise<void>;

export function UpdateProfileName(arg1:string,arg2:string):Promise<void>;
